version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: crane
      MYSQL_USER: crane
      MYSQL_PASSWORD: crane
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql

  php:
    image: fortis/stackd-php
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:7000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0
    volumes:
      - ./:/var/www/html
    command: sh -c "composer install && php-fpm"

  nginx:
    image: fortis/stackd-nginx
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web
    volumes_from:
      - php
    ports:
      - "8080:80"
