version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: crane
      MYSQL_USER: crane
      MYSQL_PASSWORD: crane
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql

  php:
    image: fortis/stackd-php
    volumes:
      - ./:/var/www/html
    command: php bin/react.php
    ports:
      - "80:7000"
